import { and, desc, eq, isNotNull, sql } from 'drizzle-orm';
import { runWithTenant } from '../../db/tenantContext';
import { abdmCareContexts, patients, visits, type AbdmCareContext } from '../../db/schema';
import { AppError } from '../../http/error';
import { logger } from '../../config/logger';
import { writeAudit } from '../audit/audit.service';

/**
 * Care contexts — the unit ABDM links, discovers and later shares (ADR-087, Milestone 2).
 *
 * A care context is a *pointer*, never content: an opaque reference plus a label. The HIE-CM is
 * data blind by design, so the single most important rule in this file is that **nothing clinical
 * ever reaches `displayLabel`**. That is enforced here rather than trusted to callers — the label
 * is composed from the visit's date and type, and `assertNonClinicalLabel` refuses anything that
 * was built some other way.
 *
 * One care context per visit. A visit that produces a prescription, a lab report and an invoice is
 * one context carrying three HI types, not three contexts — which is both what ABDM recommends and
 * what a patient looking for "my visit on the 3rd" expects to find.
 */

/**
 * The HI types this hospital can actually produce today — seven of ABDM's eight.
 *
 * `WellnessRecord` is included because we hold discrete vitals (BP, pulse, respiratory rate,
 * temperature, weight, height) on every consultation, so a wellness record is real measured data
 * rather than a stub. `DischargeSummary` is the one genuine gap: it needs an inpatient admission
 * and the IPD module does not exist. It stays absent rather than being emitted empty — an empty
 * clinical document is a claim the product cannot back — and is an open question for NHA in
 * `BACKLOG.md`.
 */
export const SUPPORTED_HI_TYPES = [
  'Prescription',
  'DiagnosticReport',
  'OPConsultation',
  'ImmunizationRecord',
  'HealthDocumentRecord',
  'WellnessRecord',
  'Invoice',
] as const;

export type HiType = (typeof SUPPORTED_HI_TYPES)[number];

/**
 * Refuses a label that could carry clinical meaning.
 *
 * Deliberately crude, and deliberately a hard failure rather than a sanitiser: the correct labels
 * are generated by `labelForVisit` below, so anything tripping this check is a caller that built a
 * label some other way — a bug to fix at the source, not to quietly scrub. Sending a diagnosis to
 * the consent manager is a disclosure we cannot take back.
 */
const CLINICAL_WORDS =
  /\b(diabet|hyperten|cancer|carcinom|tumou?r|hiv|aids|tuberculos|\btb\b|pregnan|abortion|psychiatr|depress|anxiet|schizo|positive|negative|reactive|mg\/dl|mmol|diagnos|prescri\w*\s+for)/i;

export function assertNonClinicalLabel(label: string): void {
  if (CLINICAL_WORDS.test(label)) {
    throw new AppError(
      422,
      'ABDM_LABEL_NOT_ALLOWED',
      'A care context label must not contain clinical information — ABDM is data blind by design',
    );
  }
}

/** `03/10/2026` — the platform's date format (ADR-046), built here without a client-side helper. */
function formatDate(value: Date | string): string {
  const d = typeof value === 'string' ? new Date(`${value}T00:00:00Z`) : value;
  const pad = (n: number) => String(n).padStart(2, '0');
  return `${pad(d.getUTCDate())}/${pad(d.getUTCMonth() + 1)}/${d.getUTCFullYear()}`;
}

/**
 * The label the patient sees in their PHR app.
 *
 * Date and setting only. It has to be enough for someone to recognise "that's my visit last
 * Tuesday" and not enough for anyone reading the consent manager's records to learn anything about
 * their health.
 */
export function labelForVisit(visitDate: Date | string, setting = 'OPD'): string {
  return `${setting} records from ${formatDate(visitDate)}`;
}

/**
 * Creates the care context for a visit, or adds an HI type to the one that already exists.
 *
 * Idempotent by `(tenant, referenceNumber)`, because it is driven by domain events: a visit that
 * gets a prescription and then a lab result fires twice, and the second must extend the first
 * rather than collide with it. A context already linked to ABDM stays linked and is marked for a
 * re-notification instead of being recreated.
 */
export async function recordCareContext(input: {
  tenantId: string;
  patientId: string;
  visitId?: string | null;
  branchId?: string | null;
  referenceNumber: string;
  displayLabel: string;
  hiType: HiType;
}): Promise<AbdmCareContext> {
  assertNonClinicalLabel(input.displayLabel);

  return runWithTenant(input.tenantId, async (tx) => {
    const rows = await tx
      .insert(abdmCareContexts)
      .values({
        tenantId: input.tenantId,
        patientId: input.patientId,
        visitId: input.visitId ?? null,
        branchId: input.branchId ?? null,
        referenceNumber: input.referenceNumber,
        displayLabel: input.displayLabel,
        hiTypes: [input.hiType],
      })
      .onConflictDoUpdate({
        target: [abdmCareContexts.tenantId, abdmCareContexts.referenceNumber],
        set: {
          // Append the type only if it is genuinely new, so repeated events do not grow the array.
          hiTypes: sql`(
            select array_agg(distinct t) from unnest(${abdmCareContexts.hiTypes} || ARRAY[${input.hiType}]::text[]) as t
          )`,
          updatedAt: new Date(),
        },
      })
      .returning();
    return rows[0]!;
  });
}

/**
 * The care context for a visit, built from the visit itself.
 *
 * The reference number is the visit id: already unique per tenant, already the thing every record
 * in that visit hangs off, and meaningless to anyone outside this system — which is exactly what an
 * opaque reference should be.
 */
export async function recordCareContextForVisit(
  tenantId: string,
  visitId: string,
  hiType: HiType,
): Promise<AbdmCareContext | null> {
  const visit = await runWithTenant(tenantId, async (tx) => {
    const rows = await tx
      .select({
        id: visits.id,
        patientId: visits.patientId,
        branchId: visits.branchId,
        visitDate: visits.visitDate,
      })
      .from(visits)
      .where(and(eq(visits.tenantId, tenantId), eq(visits.id, visitId)))
      .limit(1);
    return rows[0] ?? null;
  });

  if (!visit) {
    // A record whose visit has vanished is a data problem, not a linking problem: log it and move
    // on rather than failing the clinical action that triggered this.
    logger.warn({ tenantId, visitId }, 'ABDM care context skipped — visit not found');
    return null;
  }

  return recordCareContext({
    tenantId,
    patientId: visit.patientId,
    visitId: visit.id,
    branchId: visit.branchId,
    referenceNumber: visit.id,
    displayLabel: labelForVisit(visit.visitDate),
    hiType,
  });
}

/** Care contexts for one patient, newest first — what the desk and the discovery flow both read. */
export async function listCareContexts(
  tenantId: string,
  patientId: string,
): Promise<AbdmCareContext[]> {
  return runWithTenant(tenantId, (tx) =>
    tx
      .select()
      .from(abdmCareContexts)
      .where(
        and(eq(abdmCareContexts.tenantId, tenantId), eq(abdmCareContexts.patientId, patientId)),
      )
      .orderBy(desc(abdmCareContexts.createdAt)),
  );
}

/**
 * Contexts waiting to be linked to an ABHA.
 *
 * Only for patients who actually have a **verified** ABHA address: a hand-typed one was never
 * proved (ADR-084), and linking a national health record on the strength of an unverified string
 * would attach one person's records to another person's identity.
 */
export async function listLinkableCareContexts(tenantId: string, limit = 50) {
  return runWithTenant(tenantId, (tx) =>
    tx
      .select({
        careContext: abdmCareContexts,
        abhaAddress: patients.abhaAddress,
        abhaNumber: patients.abhaNumber,
      })
      .from(abdmCareContexts)
      .innerJoin(patients, eq(patients.id, abdmCareContexts.patientId))
      .where(
        and(
          eq(abdmCareContexts.tenantId, tenantId),
          eq(abdmCareContexts.status, 'pending'),
          isNotNull(patients.abhaAddress),
          isNotNull(patients.abhaVerifiedAt),
        ),
      )
      .limit(limit),
  );
}

/** Records the outcome of a link attempt. Failure is kept, not swallowed — it has to be diagnosable. */
export async function markLinkResult(
  tenantId: string,
  careContextId: string,
  result: { linked: boolean; abhaAddress?: string; error?: string },
): Promise<void> {
  await runWithTenant(tenantId, (tx) =>
    tx
      .update(abdmCareContexts)
      .set({
        status: result.linked ? 'linked' : 'failed',
        linkedAt: result.linked ? new Date() : null,
        abhaAddress: result.abhaAddress ?? null,
        lastError: result.error?.slice(0, 300) ?? null,
        linkAttempts: sql`${abdmCareContexts.linkAttempts} + 1`,
        updatedAt: new Date(),
      })
      .where(and(eq(abdmCareContexts.tenantId, tenantId), eq(abdmCareContexts.id, careContextId))),
  );

  await writeAudit({
    tenantId,
    actorUserId: null,
    action: result.linked ? 'abdm.care_context.linked' : 'abdm.care_context.link_failed',
    resourceType: 'abdm_care_context',
    resourceId: careContextId,
    severity: result.linked ? 'info' : 'warning',
    metadata: { abhaAddress: result.abhaAddress, error: result.error },
  });
}
