/**
 * Does Fidelius actually work here — and does OUR call of it round-trip?
 *
 * This is the check that has been missing since M2 was built. Every encrypted transfer in M2 and M3
 * has run in mock mode, where `cipher.ts` returns a clearly-marked `MOCK-NOT-ENCRYPTED:` envelope.
 * The real invocation — argument order, the `--filepath` handoff, the shape of what comes back —
 * was written from NHA's documentation and, for months, had never executed once.
 *
 * **It contacts nothing.** No gateway, no ABHA host, no database. It generates two key pairs, plays
 * both sides of an exchange against the locally-installed CLI, and checks the plaintext survives.
 * That makes it safe to run on staging or production, and it is the only script here of which that
 * is true: `abdm:m2check` and `abdm:m3check` write fictional patients and refuse outside development.
 *
 * What a pass proves:
 *   · the JRE and the Fidelius launcher are installed and runnable by this user
 *   · `FIDELIUS_CLI_PATH` points at something that behaves like the CLI
 *   · our `se` and `d` argument orders are right — the sender/requester pairing is easy to invert,
 *     and inverting it produces ciphertext no HIU can read
 *   · the `--filepath` handoff works for a payload larger than a command line can carry, which is
 *     every real FHIR bundle
 *   · the parameter file holding the plaintext and our private key is cleaned up afterwards
 *
 *   npm run abdm:fidelius-check -w hms_backend
 *
 * Requires ABDM_PROVIDER=gateway: in mock mode `cipher.ts` deliberately never reaches the CLI, so a
 * mock run would pass while proving nothing.
 */

import { readdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { env } from '../config/env';
import {
  contentChecksum,
  decryptFromHip,
  encryptForHiu,
  generateKeyPair,
} from '../modules/abdm/cipher';

const ok = (m: string, detail?: string): void => {
  console.log(`  ✓ ${m}`);
  if (detail) console.log(`    ${detail}`);
};
const bad = (m: string, detail?: string): void => {
  console.log(`  ✗ ${m}`);
  if (detail) console.log(`    ${detail}`);
};

/**
 * A payload big enough to be impossible as a command argument.
 *
 * NHA documents `--filepath` for a terminal's 8192-character limit. A structured FHIR bundle for one
 * consultation clears that comfortably, so the check has to as well — a 40-character test string
 * would pass without ever exercising the path production uses.
 */
function bigBundle(): string {
  const entries = Array.from({ length: 60 }, (_, i) => ({
    fullUrl: `urn:uuid:0000-${String(i).padStart(4, '0')}`,
    resource: {
      resourceType: 'Observation',
      id: `obs-${i}`,
      status: 'final',
      code: {
        coding: [{ system: 'http://loinc.org', code: '85354-9', display: 'Blood pressure panel' }],
      },
      valueQuantity: { value: 118 + (i % 9), unit: 'mm[Hg]', system: 'http://unitsofmeasure.org' },
      note: [
        { text: `Synthetic observation ${i} — generated by abdm:fidelius-check, no real patient.` },
      ],
    },
  }));
  return JSON.stringify({ resourceType: 'Bundle', type: 'document', entry: entries });
}

async function strayParameterDirs(): Promise<number> {
  const entries = await readdir(tmpdir(), { withFileTypes: true }).catch(() => []);
  return entries.filter((e) => e.isDirectory() && e.name.startsWith('fidelius-')).length;
}

async function main(): Promise<void> {
  console.log('\nFidelius round-trip check');
  console.log('-------------------------');
  console.log(`  provider   ${env.ABDM_PROVIDER}`);
  console.log(`  cli path   ${env.FIDELIUS_CLI_PATH ?? '(unset)'}`);
  console.log('  contacts   nothing — no gateway, no database\n');

  if (env.ABDM_PROVIDER !== 'gateway') {
    bad(
      `ABDM_PROVIDER is '${env.ABDM_PROVIDER}'.`,
      'In mock mode cipher.ts never reaches the CLI, so this would pass while proving nothing. Run with ABDM_PROVIDER=gateway.',
    );
    process.exit(1);
  }
  if (!env.FIDELIUS_CLI_PATH) {
    bad(
      'FIDELIUS_CLI_PATH is not set.',
      'Point it at the bin/fidelius-cli LAUNCHER from the release, not at a jar — the distribution is a script plus a lib/ directory.',
    );
    process.exit(1);
  }

  const before = await strayParameterDirs();
  const plaintext = bigBundle();
  console.log(`1. Key material  (payload for this run: ${plaintext.length} characters)`);

  // The HIU's half of the exchange. Generated here so both sides are known and the round trip can
  // actually be checked, which is the whole point.
  const hiu = await generateKeyPair();
  ok(
    'generate-key-material returned a key pair for the requester',
    `public key ${hiu.publicKey.slice(0, 24)}…`,
  );
  if (!hiu.x509PublicKey) {
    bad(
      'no x509PublicKey returned',
      'Some HIUs accept only this form in key material. Check the CLI version.',
    );
  } else {
    ok('an X.509 public key came back too', 'which is the form sent in keyMaterial (ADR-107)');
  }

  console.log('\n2. Encrypting as the HIP');
  const sealed = await encryptForHiu({
    plaintext,
    hiuPublicKey: hiu.publicKey,
    hiuNonce: hiu.nonce,
  });
  if (sealed.content.startsWith('MOCK-NOT-ENCRYPTED') || sealed.content.includes('MOCK')) {
    bad(
      'the mock envelope came back',
      'cipher.ts did not take the gateway path. Nothing was encrypted.',
    );
    process.exit(1);
  }
  ok('ciphertext produced', `${sealed.content.length} characters`);
  ok('a checksum of the PLAINTEXT is carried', sealed.checksum);
  ok('key material names the curve ABDM expects', sealed.keyMaterial.dhPublicKey.parameters);

  console.log('\n3. Decrypting as the HIU — the half that proves the argument order');
  const back = await decryptFromHip({
    ciphertext: sealed.content,
    ourPrivateKey: hiu.privateKey,
    ourNonce: hiu.nonce,
    hipPublicKey: sealed.keyMaterial.dhPublicKey.keyValue,
    hipNonce: sealed.keyMaterial.nonce,
  });

  if (back !== plaintext) {
    bad(
      'the round trip did NOT return the original bundle',
      'Ciphertext no HIU could read. Check the sender/requester pairing in cipher.ts against NHA’s worked example.',
    );
    process.exit(1);
  }
  ok('the bundle survived the round trip byte for byte');

  if (contentChecksum(back) !== sealed.checksum) {
    bad('checksum mismatch after decryption');
    process.exit(1);
  }
  ok('the checksum matches what a HIU would verify');

  console.log('\n4. What was left on disk');
  const after = await strayParameterDirs();
  if (after > before) {
    bad(
      `${after - before} Fidelius parameter directory/directories remain`,
      'They hold the plaintext bundle and a private key. Remove them, and treat this as a defect.',
    );
    process.exit(1);
  }
  ok('nothing left behind — the parameter file was removed');

  console.log('\n------------------------------------------------------------');
  console.log('Fidelius works here, and our call of it round-trips.');
  console.log('');
  console.log('This proves the encryption layer only. Still separate from it:');
  console.log('  · that ABDM can reach us (needs the HIP service registered)');
  console.log('  · that a real HIU accepts our key material');
  console.log('');
}

main().catch((err: unknown) => {
  console.error('\nfidelius-check failed:', err instanceof Error ? err.message : err);
  console.error(
    '\nA refusal here means no health data would be sent — which is the safe direction.',
  );
  process.exit(1);
});
