import { pgTable, uuid, varchar, text, timestamp, jsonb, index, unique, integer } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import { tenants } from './tenants';
import { patients } from './patients';
import { visits } from './visits';

/**
 * ABDM Milestone 2 — the HIP side: care contexts and consent artefacts (ADR-087).
 *
 * M1 proved who the patient is. M2 makes this hospital a **Health Information Provider**: the
 * records it creates become discoverable, and — with the patient's consent — shareable. Two
 * principles run through both tables and are not negotiable:
 *
 * 1. **The HIE-CM is data blind by design.** Nothing clinical may travel to ABDM in a care
 *    context: only an opaque reference and a label a human can recognise. "OPD records from
 *    03/10/2026" is correct; "Diabetes follow-up" is a disclosure. `display_label` is therefore
 *    generated by us from the visit date and type, never from a diagnosis, a drug or a result.
 * 2. **A consent artefact is deleted when it is revoked or expires**, not flagged inactive. NHA's
 *    certification checks the row is actually gone. That coexists with invariant #6 (audit records
 *    are never deleted) because the two are separate: the audit log keeps the *event* — who
 *    granted, who revoked, when — while the artefact itself is purged.
 */

/**
 * A care context: one bundle of records, as ABDM sees it.
 *
 * **One per visit** (the shape ABDM recommends, and the one that matches how a hospital actually
 * works) rather than one per record — a single OPD visit routinely produces a prescription, a lab
 * report and an invoice, and a patient looking for "my visit on the 3rd" expects one entry, not
 * three.
 *
 * That is why `hi_types` is an **array** rather than the single `hi_type` a naive reading suggests.
 * ABDM's link payload groups care contexts under an `hiType` per patient block, so one context
 * carrying three types is emitted as three blocks referencing the same context — the grouping is a
 * wire-format detail, not a reason to fragment the model the patient sees.
 */
export const abdmCareContexts = pgTable(
  'abdm_care_contexts',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    tenantId: uuid('tenant_id')
      .notNull()
      .references(() => tenants.id, { onDelete: 'restrict' }),
    branchId: uuid('branch_id'),
    patientId: uuid('patient_id')
      .notNull()
      .references(() => patients.id, { onDelete: 'restrict' }),
    /**
     * The visit this context covers. Nullable because an inpatient admission will populate it
     * differently once IPD exists, and because a document uploaded outside any visit still needs
     * somewhere to live.
     */
    visitId: uuid('visit_id').references(() => visits.id, { onDelete: 'restrict' }),
    /**
     * What ABDM quotes back at us to ask for this data. Opaque to them, stable and meaningful to
     * us. Unique per tenant, because a collision would hand one patient's records to another.
     */
    referenceNumber: varchar('reference_number', { length: 64 }).notNull(),
    /** Human-readable and deliberately non-clinical — see the file header. */
    displayLabel: varchar('display_label', { length: 200 }).notNull(),
    /** Prescription | DiagnosticReport | OPConsultation | Invoice | ImmunizationRecord | … */
    hiTypes: text('hi_types').array().notNull().default(sql`ARRAY[]::text[]`),
    /** Snapshot of the address it was linked to — the patient's ABHA may change later. */
    abhaAddress: varchar('abha_address', { length: 80 }),
    /** pending | linked | failed | not_linkable */
    status: varchar('status', { length: 20 }).notNull().default('pending'),
    linkedAt: timestamp('linked_at', { withTimezone: true }),
    /** Last failure from ABDM, kept so a stuck context can be diagnosed without re-running it. */
    lastError: varchar('last_error', { length: 300 }),
    linkAttempts: integer('link_attempts').notNull().default(0),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    tenantRefUnique: unique('abdm_care_contexts_tenant_ref_unique').on(t.tenantId, t.referenceNumber),
    byPatient: index('abdm_care_contexts_patient_idx').on(t.tenantId, t.patientId),
    byStatus: index('abdm_care_contexts_status_idx').on(t.tenantId, t.status),
    byVisit: index('abdm_care_contexts_visit_idx').on(t.tenantId, t.visitId),
  }),
);

/**
 * A consent artefact granted by a patient, as held by us (the HIP).
 *
 * We never create these — a Health Information User requests, the patient grants on their own PHR
 * app, and the artefact arrives here as a notification. Our obligations are narrow and testable:
 * store it, honour its limits on every transfer, and **delete it** the moment it is revoked or
 * expires.
 *
 * `care_contexts` is stored as JSON rather than a join table on purpose: it is a **snapshot of what
 * the patient agreed to**, and it must not drift when our own records change. A foreign key would
 * quietly rewrite the terms of a consent when a care context was edited.
 */
export const abdmConsents = pgTable(
  'abdm_consents',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    tenantId: uuid('tenant_id')
      .notNull()
      .references(() => tenants.id, { onDelete: 'restrict' }),
    /** ABDM's own consent id — the handle every later request quotes. */
    consentId: varchar('consent_id', { length: 64 }).notNull(),
    abhaAddress: varchar('abha_address', { length: 80 }).notNull(),
    hipId: varchar('hip_id', { length: 64 }).notNull(),
    /** Who is allowed to receive the data. A transfer to anyone else is a breach, not a bug. */
    hiuId: varchar('hiu_id', { length: 64 }),
    consentManagerId: varchar('consent_manager_id', { length: 32 }),
    purposeCode: varchar('purpose_code', { length: 32 }),
    purposeText: varchar('purpose_text', { length: 200 }),
    /** Only these record types may be shared under this consent. */
    hiTypes: text('hi_types').array().notNull().default(sql`ARRAY[]::text[]`),
    accessMode: varchar('access_mode', { length: 16 }),
    /** The clinical date window the patient agreed to — NOT the consent's own validity. */
    dateRangeFrom: timestamp('date_range_from', { withTimezone: true }),
    dateRangeTo: timestamp('date_range_to', { withTimezone: true }),
    /** When the HIU must destroy its copy; also when this artefact stops being usable. */
    dataEraseAt: timestamp('data_erase_at', { withTimezone: true }),
    frequencyUnit: varchar('frequency_unit', { length: 16 }),
    frequencyValue: integer('frequency_value'),
    frequencyRepeats: integer('frequency_repeats'),
    /** The exact care contexts the patient named. A snapshot — see the table comment. */
    careContexts: jsonb('care_contexts'),
    /** The consent manager's signature, retained as proof of what we were told. */
    signature: text('signature'),
    grantedAt: timestamp('granted_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    // One row per consent id per tenant. Re-notification updates rather than duplicates.
    tenantConsentUnique: unique('abdm_consents_tenant_consent_unique').on(t.tenantId, t.consentId),
    byAbha: index('abdm_consents_abha_idx').on(t.tenantId, t.abhaAddress),
    byErase: index('abdm_consents_erase_idx').on(t.dataEraseAt),
  }),
);

/**
 * Link tokens — the credential that lets us attach records to somebody's ABHA (ADR-089).
 *
 * Held per ABHA address rather than per patient: the token belongs to the *national identity*, and
 * one identity can appear on more than one chart in a group of hospitals.
 *
 * **Encrypted at rest**, like every other ABDM bearer credential (ADR-084). NHA issues them with a
 * roughly six-month life, so `expires_at` is parsed from the token's own `exp` claim rather than
 * assumed — a token we believe is valid and is not produces a failed link at the moment a patient
 * is waiting for their record to appear.
 *
 * `requested_at` without `token_enc` is the normal in-between state: acquisition is asynchronous
 * (we ask, NHA calls our webhook), so a row exists before the credential does.
 */
export const abdmLinkTokens = pgTable(
  'abdm_link_tokens',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    tenantId: uuid('tenant_id')
      .notNull()
      .references(() => tenants.id, { onDelete: 'restrict' }),
    abhaAddress: varchar('abha_address', { length: 80 }).notNull(),
    /** AES-256-GCM. Null while a request is outstanding. */
    tokenEnc: text('token_enc'),
    /** From the token's own `exp` claim — never assumed. */
    expiresAt: timestamp('expires_at', { withTimezone: true }),
    requestedAt: timestamp('requested_at', { withTimezone: true }),
    /** So a webhook that never arrives is visible rather than silently retried for ever. */
    lastError: varchar('last_error', { length: 300 }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    tenantAbhaUnique: unique('abdm_link_tokens_tenant_abha_unique').on(t.tenantId, t.abhaAddress),
  }),
);

/**
 * A patient linking records they discovered themselves (ADR-090).
 *
 * The user-initiated flow is a three-step conversation with gaps in it — discover, init, confirm —
 * and the OTP we send in the middle is ours, not ABDM's. This row is what survives between the
 * steps: which patient, which contexts they chose, and the one-time code that proves the person
 * holding the phone is the person whose records they are.
 *
 * The code is stored **hashed** with an attempt counter, reusing the platform's existing OTP store
 * contract — so brute force burns the code rather than only the clock, and a leaked table hands
 * over no live codes.
 */
export const abdmLinkRequests = pgTable(
  'abdm_link_requests',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    tenantId: uuid('tenant_id')
      .notNull()
      .references(() => tenants.id, { onDelete: 'restrict' }),
    /** ABDM's transaction id — the thread that ties discover, init and confirm together. */
    transactionId: varchar('transaction_id', { length: 64 }).notNull(),
    /** Ours, quoted back by the patient's app at confirm time. */
    referenceNumber: varchar('reference_number', { length: 64 }).notNull(),
    patientId: uuid('patient_id')
      .notNull()
      .references(() => patients.id, { onDelete: 'restrict' }),
    abhaAddress: varchar('abha_address', { length: 80 }),
    /** Exactly the contexts the patient asked for — never everything we hold. */
    careContextRefs: text('care_context_refs').array().notNull().default(sql`ARRAY[]::text[]`),
    /** sms | email. The number is ours to choose; ABDM's verified one is not necessarily ours. */
    channel: varchar('channel', { length: 10 }).notNull().default('sms'),
    destination: varchar('destination', { length: 255 }).notNull(),
    codeHash: varchar('code_hash', { length: 128 }),
    expiresAt: timestamp('expires_at', { withTimezone: true }),
    attempts: integer('attempts').notNull().default(0),
    consumedAt: timestamp('consumed_at', { withTimezone: true }),
    /** pending | verified | failed | expired */
    status: varchar('status', { length: 16 }).notNull().default('pending'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    tenantRefUnique: unique('abdm_link_requests_tenant_ref_unique').on(t.tenantId, t.referenceNumber),
    byTxn: index('abdm_link_requests_txn_idx').on(t.tenantId, t.transactionId),
  }),
);

/**
 * One health-information transfer, from request to acknowledgement (ADR-091).
 *
 * Kept because a transfer is the moment clinical records leave the hospital: what was sent, to
 * whom, under which consent, and whether it arrived is exactly what an audit — or a patient asking
 * "who has seen my records?" — needs to be answerable from.
 *
 * **The HIU's push URL and public key are stored, the records are not.** The job reads the clinical
 * data when it runs, so a queued or failed transfer never leaves a copy of somebody's chart sitting
 * in a work table.
 */
export const abdmDataTransfers = pgTable(
  'abdm_data_transfers',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    tenantId: uuid('tenant_id')
      .notNull()
      .references(() => tenants.id, { onDelete: 'restrict' }),
    /** ABDM's id for the whole data flow. */
    transactionId: varchar('transaction_id', { length: 64 }).notNull(),
    requestId: varchar('request_id', { length: 64 }),
    consentId: varchar('consent_id', { length: 64 }).notNull(),
    /** Where the HIU wants the data — deliberately not restricted to an allowlist (ADR-091). */
    dataPushUrl: varchar('data_push_url', { length: 500 }).notNull(),
    hiuPublicKey: text('hiu_public_key'),
    hiuNonce: varchar('hiu_nonce', { length: 200 }),
    careContextRefs: text('care_context_refs').array().notNull().default(sql`ARRAY[]::text[]`),
    dateRangeFrom: timestamp('date_range_from', { withTimezone: true }),
    dateRangeTo: timestamp('date_range_to', { withTimezone: true }),
    /** received | acknowledged | transferred | refused | failed */
    status: varchar('status', { length: 16 }).notNull().default('received'),
    /** Why a refusal happened, in words an auditor can read. */
    reason: varchar('reason', { length: 300 }),
    entriesSent: integer('entries_sent').notNull().default(0),
    /** NHA's clock starts when the request arrives, so the deadline is stored, not inferred. */
    deadlineAt: timestamp('deadline_at', { withTimezone: true }),
    completedAt: timestamp('completed_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    tenantTxnUnique: unique('abdm_data_transfers_tenant_txn_unique').on(t.tenantId, t.transactionId),
    byStatus: index('abdm_data_transfers_status_idx').on(t.tenantId, t.status),
  }),
);

export type AbdmDataTransfer = typeof abdmDataTransfers.$inferSelect;

export type AbdmLinkRequest = typeof abdmLinkRequests.$inferSelect;

export type AbdmLinkToken = typeof abdmLinkTokens.$inferSelect;

export type AbdmCareContext = typeof abdmCareContexts.$inferSelect;
export type NewAbdmCareContext = typeof abdmCareContexts.$inferInsert;
export type AbdmConsent = typeof abdmConsents.$inferSelect;
